# fly.toml app configuration file generated for crowe-crypto on 2025-09-14T04:10:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crowe-crypto'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
